# Generated by Django 6.0.3 on 2026-03-28 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_url', models.URLField(blank=True, default='#', verbose_name='GitHub链接')),
                ('wechat_id', models.CharField(blank=True, default='', max_length=100, verbose_name='微信号')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='邮箱地址')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '站点配置',
                'verbose_name_plural': '站点配置',
            },
        ),
    ]
