# Generated by Django 6.0.3 on 2026-03-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_siteconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='friend_link_1_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='友情链接1名称'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='friend_link_1_url',
            field=models.URLField(blank=True, default='', verbose_name='友情链接1地址'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='friend_link_2_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='友情链接2名称'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='friend_link_2_url',
            field=models.URLField(blank=True, default='', verbose_name='友情链接2地址'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='friend_link_3_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='友情链接3名称'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='friend_link_3_url',
            field=models.URLField(blank=True, default='', verbose_name='友情链接3地址'),
        ),
    ]
