# Generated by Django 6.0.3 on 2026-03-28 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_siteconfig_friend_link_1_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='site/', verbose_name='头像'),
        ),
    ]
