# Generated by Django 6.0.3 on 2026-03-28 13:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_postlike'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, unique=True, verbose_name='日期')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='访问次数')),
            ],
            options={
                'verbose_name': '日访问量',
                'verbose_name_plural': '日访问量',
                'ordering': ['-date'],
            },
        ),
    ]
