# Generated by Django 6.0.3 on 2026-03-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_dailyvisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='tech_1',
            field=models.CharField(blank=True, choices=[('python', 'Python'), ('django', 'Django'), ('java', 'Java'), ('spring', 'Spring'), ('go', 'Go'), ('rust', 'Rust'), ('nodejs', 'Node.js'), ('react', 'React'), ('vue', 'Vue'), ('angular', 'Angular'), ('typescript', 'TypeScript'), ('javascript', 'JavaScript'), ('html5', 'HTML5'), ('css3', 'CSS3'), ('tailwind', 'Tailwind CSS'), ('bootstrap', 'Bootstrap'), ('mysql', 'MySQL'), ('postgresql', 'PostgreSQL'), ('mongodb', 'MongoDB'), ('redis', 'Redis'), ('elasticsearch', 'Elasticsearch'), ('docker', 'Docker'), ('kubernetes', 'Kubernetes'), ('aws', 'AWS'), ('linux', 'Linux'), ('nginx', 'Nginx'), ('git', 'Git'), ('webpack', 'Webpack')], default='python', max_length=20, verbose_name='技术栈1'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='tech_2',
            field=models.CharField(blank=True, choices=[('python', 'Python'), ('django', 'Django'), ('java', 'Java'), ('spring', 'Spring'), ('go', 'Go'), ('rust', 'Rust'), ('nodejs', 'Node.js'), ('react', 'React'), ('vue', 'Vue'), ('angular', 'Angular'), ('typescript', 'TypeScript'), ('javascript', 'JavaScript'), ('html5', 'HTML5'), ('css3', 'CSS3'), ('tailwind', 'Tailwind CSS'), ('bootstrap', 'Bootstrap'), ('mysql', 'MySQL'), ('postgresql', 'PostgreSQL'), ('mongodb', 'MongoDB'), ('redis', 'Redis'), ('elasticsearch', 'Elasticsearch'), ('docker', 'Docker'), ('kubernetes', 'Kubernetes'), ('aws', 'AWS'), ('linux', 'Linux'), ('nginx', 'Nginx'), ('git', 'Git'), ('webpack', 'Webpack')], default='django', max_length=20, verbose_name='技术栈2'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='tech_3',
            field=models.CharField(blank=True, choices=[('python', 'Python'), ('django', 'Django'), ('java', 'Java'), ('spring', 'Spring'), ('go', 'Go'), ('rust', 'Rust'), ('nodejs', 'Node.js'), ('react', 'React'), ('vue', 'Vue'), ('angular', 'Angular'), ('typescript', 'TypeScript'), ('javascript', 'JavaScript'), ('html5', 'HTML5'), ('css3', 'CSS3'), ('tailwind', 'Tailwind CSS'), ('bootstrap', 'Bootstrap'), ('mysql', 'MySQL'), ('postgresql', 'PostgreSQL'), ('mongodb', 'MongoDB'), ('redis', 'Redis'), ('elasticsearch', 'Elasticsearch'), ('docker', 'Docker'), ('kubernetes', 'Kubernetes'), ('aws', 'AWS'), ('linux', 'Linux'), ('nginx', 'Nginx'), ('git', 'Git'), ('webpack', 'Webpack')], default='tailwind', max_length=20, verbose_name='技术栈3'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='tech_4',
            field=models.CharField(blank=True, choices=[('python', 'Python'), ('django', 'Django'), ('java', 'Java'), ('spring', 'Spring'), ('go', 'Go'), ('rust', 'Rust'), ('nodejs', 'Node.js'), ('react', 'React'), ('vue', 'Vue'), ('angular', 'Angular'), ('typescript', 'TypeScript'), ('javascript', 'JavaScript'), ('html5', 'HTML5'), ('css3', 'CSS3'), ('tailwind', 'Tailwind CSS'), ('bootstrap', 'Bootstrap'), ('mysql', 'MySQL'), ('postgresql', 'PostgreSQL'), ('mongodb', 'MongoDB'), ('redis', 'Redis'), ('elasticsearch', 'Elasticsearch'), ('docker', 'Docker'), ('kubernetes', 'Kubernetes'), ('aws', 'AWS'), ('linux', 'Linux'), ('nginx', 'Nginx'), ('git', 'Git'), ('webpack', 'Webpack')], default='mysql', max_length=20, verbose_name='技术栈4'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='tech_5',
            field=models.CharField(blank=True, choices=[('python', 'Python'), ('django', 'Django'), ('java', 'Java'), ('spring', 'Spring'), ('go', 'Go'), ('rust', 'Rust'), ('nodejs', 'Node.js'), ('react', 'React'), ('vue', 'Vue'), ('angular', 'Angular'), ('typescript', 'TypeScript'), ('javascript', 'JavaScript'), ('html5', 'HTML5'), ('css3', 'CSS3'), ('tailwind', 'Tailwind CSS'), ('bootstrap', 'Bootstrap'), ('mysql', 'MySQL'), ('postgresql', 'PostgreSQL'), ('mongodb', 'MongoDB'), ('redis', 'Redis'), ('elasticsearch', 'Elasticsearch'), ('docker', 'Docker'), ('kubernetes', 'Kubernetes'), ('aws', 'AWS'), ('linux', 'Linux'), ('nginx', 'Nginx'), ('git', 'Git'), ('webpack', 'Webpack')], default='', max_length=20, verbose_name='技术栈5'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='tech_6',
            field=models.CharField(blank=True, choices=[('python', 'Python'), ('django', 'Django'), ('java', 'Java'), ('spring', 'Spring'), ('go', 'Go'), ('rust', 'Rust'), ('nodejs', 'Node.js'), ('react', 'React'), ('vue', 'Vue'), ('angular', 'Angular'), ('typescript', 'TypeScript'), ('javascript', 'JavaScript'), ('html5', 'HTML5'), ('css3', 'CSS3'), ('tailwind', 'Tailwind CSS'), ('bootstrap', 'Bootstrap'), ('mysql', 'MySQL'), ('postgresql', 'PostgreSQL'), ('mongodb', 'MongoDB'), ('redis', 'Redis'), ('elasticsearch', 'Elasticsearch'), ('docker', 'Docker'), ('kubernetes', 'Kubernetes'), ('aws', 'AWS'), ('linux', 'Linux'), ('nginx', 'Nginx'), ('git', 'Git'), ('webpack', 'Webpack')], default='', max_length=20, verbose_name='技术栈6'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='tech_7',
            field=models.CharField(blank=True, choices=[('python', 'Python'), ('django', 'Django'), ('java', 'Java'), ('spring', 'Spring'), ('go', 'Go'), ('rust', 'Rust'), ('nodejs', 'Node.js'), ('react', 'React'), ('vue', 'Vue'), ('angular', 'Angular'), ('typescript', 'TypeScript'), ('javascript', 'JavaScript'), ('html5', 'HTML5'), ('css3', 'CSS3'), ('tailwind', 'Tailwind CSS'), ('bootstrap', 'Bootstrap'), ('mysql', 'MySQL'), ('postgresql', 'PostgreSQL'), ('mongodb', 'MongoDB'), ('redis', 'Redis'), ('elasticsearch', 'Elasticsearch'), ('docker', 'Docker'), ('kubernetes', 'Kubernetes'), ('aws', 'AWS'), ('linux', 'Linux'), ('nginx', 'Nginx'), ('git', 'Git'), ('webpack', 'Webpack')], default='', max_length=20, verbose_name='技术栈7'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='tech_8',
            field=models.CharField(blank=True, choices=[('python', 'Python'), ('django', 'Django'), ('java', 'Java'), ('spring', 'Spring'), ('go', 'Go'), ('rust', 'Rust'), ('nodejs', 'Node.js'), ('react', 'React'), ('vue', 'Vue'), ('angular', 'Angular'), ('typescript', 'TypeScript'), ('javascript', 'JavaScript'), ('html5', 'HTML5'), ('css3', 'CSS3'), ('tailwind', 'Tailwind CSS'), ('bootstrap', 'Bootstrap'), ('mysql', 'MySQL'), ('postgresql', 'PostgreSQL'), ('mongodb', 'MongoDB'), ('redis', 'Redis'), ('elasticsearch', 'Elasticsearch'), ('docker', 'Docker'), ('kubernetes', 'Kubernetes'), ('aws', 'AWS'), ('linux', 'Linux'), ('nginx', 'Nginx'), ('git', 'Git'), ('webpack', 'Webpack')], default='', max_length=20, verbose_name='技术栈8'),
        ),
    ]
