# Generated by Django 6.0.3 on 2026-03-28 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_siteconfig_tech_1_siteconfig_tech_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('code', models.CharField(max_length=6, verbose_name='验证码')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_used', models.BooleanField(default=False, verbose_name='已使用')),
                ('fail_count', models.PositiveIntegerField(default=0, verbose_name='失败次数')),
                ('locked_until', models.DateTimeField(blank=True, null=True, verbose_name='锁定至')),
            ],
            options={
                'verbose_name': '密码重置验证码',
                'verbose_name_plural': '密码重置验证码',
                'ordering': ['-created_at'],
            },
        ),
    ]
